[context.production.environment]
  HUGO_VERSION = "0.55.5"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.55.5"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.55.5"
